### PR TITLE
Fix stale UseRequestServices

### PR DESCRIPTION
**Pull request by HaoK**
cc @Tratcher

### CODE REVIEW

**Comment by Tratcher** [comment]
You also need to remove RequestContainer from the project.json.

**Comment by Tratcher** [comment]
There are at least three references in the repo.

**Comment by HaoK** [comment]
Updated PR removing references

**Comment by Tratcher** [comment]
:shipit:

**Comment by HaoK** [comment]
594642b5013137f9d90b8a76a908cbd389357b50

**Pull request closed without merging**
