### PR TITLE
Fix JSON patch test

### PR DESCRIPTION
**Pull request by jbagga**
@ryanbrandenburg Can you try building it locally? I could not run Entropy tests locally.

Or I can wait for https://github.com/aspnet/Entropy/pull/271 to be checked in and then merge this in once I know it passes.

### CODE REVIEW

**Comment by ryanbrandenburg** [comment]
Yeah, you might just wait on #271, that way we can be sure it fixes it.

**Comment by jbagga** [comment]
@ryanbrandenburg Can you restart the Mac tests?

**Comment by ryanbrandenburg** [comment]
I restarted it, but if the only failure you get is the stupid CuRL OSX only thing then feel free to merge, Nate and I are considering not even running OSX in Travis since it's so unreliable.

**Comment by jbagga** [comment]
@ryanbrandenburg Same error again. Merging now

**Pull request merged**
