### PR TITLE
Add custom options classes sample

### PR DESCRIPTION
**Pull request by shaunluttin**
https://github.com/aspnet/Configuration/pull/539
https://github.com/aspnet/Configuration/issues/538
@Rick-Anderson

### CODE REVIEW

**Comment by shaunluttin** [comment]
@Rick-Anderson Is this PR of interest?

**Comment by Rick-Anderson** [comment]
@danroth27  can you get someone to review this PR?

**Comment by Eilon** [comment]
Closing because we are not planning to add this code to the repo. The Entropy repo is more about some simple sample apps that demonstrate a few key features so that the team can make sure everything is running smoothly.

**Comment by Rick-Anderson** [comment]
@shaunluttin maybe we could add this to https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration

**Comment by shaunluttin** [comment]
@Rick-Anderson Moving it there does seem appropriate. These days, though, I am working on [other career goals](http://bigfontblog.azurewebsites.net/some-career-related-ultimate-goals-for-2017/), and might reassess contribution to the .NET Core docs later this year. Thank you for following up and closing the issue.

**Pull request closed without merging**
